# IMDB Dataset Initial Data Check

This notebook performs an initial check on the IMDb datasets to:
1. Understand the structure of each dataset.
2. Identify missing values, duplicates, and potential issues.

## Step 1: Import Libraries

In this step, we import the required libraries and configure display options to ensure we can comprehensively view the dataset outputs in the notebook.

In [28]:
# Import Libraries
import pandas as pd

# Set display options for better visibility
pd.set_option('display.max_rows', None)  # Show all rows in a DataFrame
pd.set_option('display.max_columns', None)  # Show all columns in a DataFrame
pd.set_option('display.width', None)  # Expand the width of the output

## Step 2: Define the Inspection Function

The `load_and_inspect` function:
1. Loads a dataset from a file.
2. Prints its shape, columns, and a sample of rows.
3. Checks for missing values and highlights critical issues (e.g., columns with more than 50% missing values).
4. Identifies duplicate values in each column.

In [29]:
# Function to load and inspect datasets
def load_and_inspect(file_path, name, sep='\t'):
    print(f"\n--- Loading {name} ({file_path}) ---")
    df = pd.read_csv(file_path, sep=sep, dtype=str, na_values=['\\N'])
    print(f"Shape: {df.shape}")
    print(f"Columns: {df.columns.tolist()}")
    print("Sample Rows:")
    print(df.head())
    
    # Missing values
    missing_values = df.isnull().sum()
    print("\nMissing Values per Column:")
    print(missing_values)
    
    # Highlight critical missing value issues
    print("\nCritical Missing Value Issues:")
    for column, count in missing_values.items():
        if count / len(df) > 0.5:
            print(f"{column} has more than 50% missing values.")
    
    # Check for duplicate values in each column
    print("\nDuplicate Values per Column:")
    duplicate_results = {}
    for column in df.columns:
        duplicates = df.duplicated(subset=[column]).sum()
        duplicate_results[column] = duplicates
        print(f"{column}: {duplicates} duplicate values")
    
    return df

## Step 3: Define Dataset Paths

Here, we define the paths to the IMDb datasets. Ensure that the file paths match the location of the downloaded `.tsv` files on your system.

In [30]:
# Paths to datasets
data_files = {
    'Title Basics': 'data/title.basics.tsv',
    'Title AKAs': 'data/title.akas.tsv',
    'Title Ratings': 'data/title.ratings.tsv',
    'Title Crew': 'data/title.crew.tsv',
    'Title Episode': 'data/title.episode.tsv',
    'Title Principals': 'data/title.principals.tsv',
    'Name Basics': 'data/name.basics.tsv'
}

## Step 4: Load and Inspect Datasets

We iterate over each dataset using the `load_and_inspect` function to:
1. Load the dataset.
2. Perform the initial checks (missing values, duplicates, and foreign key validation).
3. Save the findings in a log file for each dataset.

In [31]:
# Load and inspect datasets
datasets = {}
for name, path in data_files.items():
    datasets[name] = load_and_inspect(path, name)

--- Loading Title Basics (data/title.basics.tsv) ---
Shape: (11326033, 9)
Columns: ['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes', 'genres']
Sample Rows:
      tconst titleType            primaryTitle           originalTitle  \
0  tt0000001     short              Carmencita              Carmencita
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens
2  tt0000003     short            Poor Pierrot          Pauvre Pierrot
3  tt0000004     short             Un bon bock             Un bon bock
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene

  isAdult startYear endYear runtimeMinutes                    genres
0       0      1894     NaN              1         Documentary,Short
1       0      1892     NaN              5           Animation,Short
2       0      1892     NaN              5  Animation,Comedy,Romance
3       0      1892     NaN             12           Animation,Short
4       0      1893     NaN              1                     Short

Missing Values per Column:
tconst                   0
titleType                0
primaryTitle            19
originalTitle           19
isAdult                  1
startYear          1418385
endYear           11192349
runtimeMinutes     7742549
genres              501220
dtype: int64

Critical Missing Value Issues:
endYear has more than 50% missing values.
runtimeMinutes has more than 50% missing values.

Duplicate Values per Column:
tconst: 0 duplicate values
titleType: 11326022 duplicate values
primaryTitle: 6236098 duplicate values
originalTitle: 6211321 duplicate values
isAdult: 11325991 duplicate values
startYear: 11325881 duplicate values
endYear: 11325936 duplicate values
runtimeMinutes: 11325081 duplicate values
genres: 11323654 duplicate values

--- Loading Title AKAs (data/title.akas.tsv) ---
Shape: (50717137, 8)
Columns: ['titleId', 'ordering', 'title', 'region', 'language', 'types', 'attributes', 'isOriginalTitle']
Sample Rows:
     titleId ordering                      title region language        types  \
0  tt0000001        1                 Carmencita    NaN      NaN     original
1  tt0000001        2                 Carmencita     DE      NaN          NaN
2  tt0000001        3                 Carmencita     US      NaN  imdbDisplay
3  tt0000001        4  Carmencita - spanyol tánc     HU      NaN  imdbDisplay
4  tt0000001        5                 Καρμενσίτα     GR      NaN  imdbDisplay

      attributes isOriginalTitle
0            NaN               1
1  literal title               0
2            NaN               0
3            NaN               0
4            NaN               0

Missing Values per Column:
titleId                   0
ordering                  0
title                    39
region             11373992
language           16724814
types              35178908
attributes         50424471
isOriginalTitle           0
dtype: int64

Critical Missing Value Issues:
types has more than 50% missing values.
attributes has more than 50% missing values.

Duplicate Values per Column:
titleId: 39424948 duplicate values
ordering: 50716886 duplicate values
title: 43487108 duplicate values
region: 50716889 duplicate values
language: 50717028 duplicate values
types: 50717113 duplicate values
attributes: 50716952 duplicate values
isOriginalTitle: 50717135 duplicate values

--- Loading Title Ratings (data/title.ratings.tsv) ---
Shape: (1514947, 3)
Columns: ['tconst', 'averageRating', 'numVotes']
Sample Rows:
      tconst averageRating numVotes
0  tt0000001           5.7     2111
1  tt0000002           5.6      284
2  tt0000003           6.4     2138
3  tt0000004           5.3      182
4  tt0000005           6.2     2866

Missing Values per Column:
tconst           0
averageRating    0
numVotes         0
dtype: int64

Critical Missing Value Issues:

Duplicate Values per Column:
tconst: 0 duplicate values
averageRating: 1514856 duplicate values
numVotes: 1492035 duplicate values

--- Loading Title Crew (data/title.crew.tsv) ---
Shape: (11328039, 3)
Columns: ['tconst', 'directors', 'writers']
Sample Rows:
      tconst  directors writers
0  tt0000001  nm0005690     NaN
1  tt0000002  nm0721526     NaN
2  tt0000003  nm0721526     NaN
3  tt0000004  nm0721526     NaN
4  tt0000005  nm0005690     NaN

Missing Values per Column:
tconst             0
directors    4900803
writers      5557116
dtype: int64

Critical Missing Value Issues:

Duplicate Values per Column:
tconst: 0 duplicate values
directors: 10394023 duplicate values
writers: 9939653 duplicate values

--- Loading Title Episode (data/title.episode.tsv) ---
Shape: (8702452, 4)
Columns: ['tconst', 'parentTconst', 'seasonNumber', 'episodeNumber']
Sample Rows:
      tconst parentTconst seasonNumber episodeNumber
0  tt0031458   tt32857063          NaN           NaN
1  tt0041951    tt0041038            1             9
2  tt0042816    tt0989125            1            17
3  tt0042889    tt0989125          NaN           NaN
4  tt0043426    tt0040051            3            42

Missing Values per Column:
tconst                 0
parentTconst           0
seasonNumber     1756886
episodeNumber    1756886
dtype: int64

Critical Missing Value Issues:

Duplicate Values per Column:
tconst: 0 duplicate values
parentTconst: 8488691 duplicate values
seasonNumber: 8702138 duplicate values
episodeNumber: 8686667 duplicate values

--- Loading Title Principals (data/title.principals.tsv) ---
Shape: (89924237, 6)
Columns: ['tconst', 'ordering', 'nconst', 'category', 'job', 'characters']
Sample Rows:
      tconst ordering     nconst         category                      job  \
0  tt0000001        1  nm1588970             self                      NaN
1  tt0000001        2  nm0005690         director                      NaN
2  tt0000001        3  nm0005690         producer                 producer
3  tt0000001        4  nm0374658  cinematographer  director of photography
4  tt0000002        1  nm0721526         director                      NaN

  characters
0   ["Self"]
1        NaN
2        NaN
3        NaN
4        NaN

Missing Values per Column:
tconst               0
ordering             0
nconst               0
category             0
job           73107386
characters    46366693
dtype: int64

Critical Missing Value Issues:
job has more than 50% missing values.
characters has more than 50% missing values.

Duplicate Values per Column:
tconst: 79656784 duplicate values
ordering: 89924162 duplicate values
nconst: 83398766 duplicate values
category: 89924224 duplicate values
job: 89880461 duplicate values
characters: 85728489 duplicate values

--- Loading Name Basics (data/name.basics.tsv) ---
Shape: (14046228, 6)
Columns: ['nconst', 'primaryName', 'birthYear', 'deathYear', 'primaryProfession', 'knownForTitles']
Sample Rows:
      nconst      primaryName birthYear deathYear  \
0  nm0000001     Fred Astaire      1899      1987
1  nm0000002    Lauren Bacall      1924      2014
2  nm0000003  Brigitte Bardot      1934       NaN
3  nm0000004     John Belushi      1949      1982
4  nm0000005   Ingmar Bergman      1918      2007

                    primaryProfession                           knownForTitles
0        actor,miscellaneous,producer  tt0050419,tt0072308,tt0053137,tt0027125
1  actress,soundtrack,archive_footage  tt0037382,tt0075213,tt0117057,tt0038355
2   actress,music_department,producer  tt0057345,tt0049189,tt0056404,tt0054452
3       actor,writer,music_department  tt0072562,tt0077975,tt0080455,tt0078723
4               writer,director,actor  tt0050986,tt0069467,tt0050976,tt0083922

Missing Values per Column:
nconst                      0
primaryName                59
birthYear            13411907
deathYear            13808092
primaryProfession     2728537
knownForTitles        1591384
dtype: int64

Critical Missing Value Issues:
birthYear has more than 50% missing values.
deathYear has more than 50% missing values.

Duplicate Values per Column:
nconst: 0 duplicate values
primaryName: 3266041 duplicate values
birthYear: 14045674 duplicate values
deathYear: 14045732 duplicate values
primaryProfession: 14023047 duplicate values
knownForTitles: 8199013 duplicate values